kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqcl2route 
  namespace: ibmmq 
spec:
  host: tls.chl.mq.ibm.com
  to:
    kind: Service
    name: mqcl2-ibm-mq 
  port:
    targetPort: 11415
  tls:
    termination: passthrough
