kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqcl2route 
  namespace: wbc9
spec:
  host: tlstwo.chl.mq.ibm.com
  to:
    kind: Service
    name: mqcl2-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
