apiVersion: v1
kind: ConfigMap
metadata:
  name: cl2-mqsc
data:
  cl.mqsc: |
    DEFINE CHANNEL(TLSTWO) CHLTYPE(SVRCONN) SSLCIPH(TLS_RSA_WITH_AES_128_CBC_SHA256) CERTLABL('label1') SSLCAUTH (OPTIONAL) REPLACE
    SET CHLAUTH(TLSTWO) TYPE(BLOCKUSER) USERLIST(nobody)
    SET CHLAUTH(TLSTWO) TYPE (ADDRESSMAP) ADDRESS(*) MCAUSER('mqm')
    DEFINE CHANNEL(CL.TWO.CONN) CHLTYPE(SVRCONN) REPLACE
    SET CHLAUTH(CL.TWO.CONN) TYPE(BLOCKUSER) USERLIST(nobody)
    SET CHLAUTH(CL.TWO.CONN) TYPE (ADDRESSMAP) ADDRESS(*) MCAUSER('mqm')
    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(NONE) ADOPTCTX(NO)
    REFRESH SECURITY TYPE(CONNAUTH)
    DEFINE QLOCAL(IVT.Q) DEFPSIST(YES) MAXDEPTH(5000000) REPLACE
    ALTER QMGR REPOS(OCPCL)
    DEFINE CHANNEL(TO.CL2) CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('mqcl2-ibm-mq.mq.svc(1414)') CLUSTER(OCPCL) REPLACE
    DEFINE CHANNEL(TO.CL1) CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('mqcl1-ibm-mq.mq.svc(1414)') CLUSTER(OCPCL) REPLACE
    DEFINE QALIAS(APPQ) TARGET(CLNQ) REPLACE
    
